# Generated by Django 3.2.4 on 2021-06-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_operations', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='likes',
            field=models.ManyToManyField(related_name='restaurant_foods', to='customer_operations.Customer'),
        ),
    ]
