# Generated by Django 3.2.4 on 2021-06-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_operations', '0001_initial'),
        ('common', '0002_food_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='customer',
        ),
        migrations.AddField(
            model_name='food',
            name='orders',
            field=models.ManyToManyField(related_name='order_foods', to='customer_operations.Customer'),
        ),
    ]
