# Generated by Django 3.2.4 on 2021-06-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(max_length=8000, null=True),
        ),
    ]
