# Generated by Django 3.2.4 on 2021-06-29 10:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_operations', '0001_initial'),
        ('common', '0006_auto_20210625_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, null=True)),
                ('message', models.TextField(max_length=8000, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_operations.customer')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.food')),
            ],
        ),
    ]
