# Generated by Django 3.2.4 on 2021-07-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
