# Generated by Django 3.2.4 on 2021-07-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_alter_food_food_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_pic',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
