# Generated by Django 3.2.4 on 2021-07-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_food_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='like_count',
            field=models.IntegerField(default=0, null=0),
            preserve_default=False,
        ),
    ]
