# Generated by Django 3.2.4 on 2021-07-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_alter_food_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='order_count',
            field=models.IntegerField(null=True),
        ),
    ]
