# Generated by Django 3.2.4 on 2021-07-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_food_order_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='rate',
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(max_length=8000, null=True),
        ),
    ]
