# Generated by Django 3.2.4 on 2021-06-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
