# Generated by Django 3.2.4 on 2021-07-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(max_length=8000, null=True),
        ),
    ]
