# Generated by Django 3.2.4 on 2021-07-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_operations', '0004_alter_restaurant_avg_int_food_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='ordered_food_count',
            field=models.IntegerField(null=True),
        ),
    ]
